#!/bin/bash

pip install --user ansiwrap==0.8.3
pip install --user asciitree==0.3.3
pip install --user asn1crypto==0.24.0
pip install --user atk==2.25.90
pip install --user attrs==18.2.0
pip install --user av
pip install --user backcall==0.1.0
pip install --user blas==1.1
pip install --user bleach==3.0.2
pip install --user bokeh==1.4.0
pip install --user boost==1.64.0
pip install --user boost-cpp==1.64.0
pip install --user boto3==1.9.73
pip install --user botocore==1.12.74
pip install --user bottleneck==1.3.2
pip install --user bzip2==1.0.6
pip install --user ca-certificates==2018.11.29
pip install --user cairo
pip install --user cairomm==1.12.2
pip install --user certifi==2018.11.29
pip install --user cffi==1.11.5
pip install --user cftime==1.0.3.4
pip install --user cgal==4.11
pip install --user chardet==3.0.4
pip install --user click==7.0
pip install --user cloudpickle==0.6.1
pip install --user colorcet==1.0.0
pip install --user cryptography==2.2.1
pip install --user cryptography-vectors==2.4.2
pip install --user curl==7.63.0
pip install --user cvxopt==1.2.1
pip install --user cvxpy
pip install --user cycler==0.10.0
pip install --user cytoolz==0.9.0.1
pip install --user dask==1
pip install --user dask-core==1.0.0
pip install --user dask-image==0.2.0
pip install --user datashader
pip install --user datashape==0.5.4
pip install --user dbus==1.13.0
pip install --user decorator==4.3.0
pip install --user dill==0.2.8.2
pip install --user distributed
pip install --user docutils==0.14
pip install --user dsdp==5.8
pip install --user ecos
pip install --user entrypoints==0.2.3
pip install --user expat==2.2.5
pip install --user fastcache==1.0.2
pip install --user fasteners==0.14.1
pip install --user ffmpeg
pip install --user fftw
pip install --user fontconfig==2.13.0
pip install --user freetype==2.8.1
pip install --user future==0.17.1
pip install --user gdk-pixbuf==2.36.12
pip install --user gettext==0.19.8.1
pip install --user giflib==5.1.4
pip install --user glib==2.55.0
pip install --user glpk==4.65
pip install --user gmp==6.1.2
pip install --user gnutls==3.5.19
pip install --user gobject-introspection==1.55.0
pip install --user graphite2==1.3.13
pip install --user graphviz==2.38.0
pip install --user gsl==2.2.1
pip install --user gst-plugins-base==1.12.5
pip install --user gstreamer==1.12.5
pip install --user h5netcdf==0.6.2
pip install --user h5py==2.8.0
pip install --user harfbuzz==1.8.5
pip install --user hdf4==4.2.13
pip install --user hdf5==1.10.2
pip install --user heapdict==1.0.0
pip install --user holoviews
pip install --user icu==58.2
pip install --user idna==2.8
pip install --user imageio==2.4.1
pip install --user ipykernel==5.1.0
pip install --user ipython
pip install --user ipython_genutils==0.2.0
pip install --user ipywidgets
pip install --user jasper==1.900.1
pip install --user jedi==0.13.2
pip install --user jinja2==2.10
pip install --user jmespath==0.9.3
pip install --user jpeg==9c
pip install --user jsonschema==3.0.0a3
pip install --user jupyter
pip install --user jupyter_client==5.2.4
pip install --user jupyter_console==6.0.0
pip install --user jupyter_core==4.4.0
pip install --user kiwisolver==1.0.1
pip install --user krb5==1.16.2
pip install --user lapack==3.6.1
pip install --user libcroco==0.6.12
pip install --user libcurl==7.63.0
pip install --user libedit==3.1.20170329
pip install --user libffi==3.2.1
pip install --user libgcc==7.2.0
pip install --user libgfortran==3.0.0
pip install --user libgfortran-ng==7.2.0
pip install --user libiconv==1.15
pip install --user libnetcdf==4.6.1
pip install --user libpng==1.6.34
pip install --user libprotobuf==3.5.2
pip install --user librsvg==2.40.19
pip install --user libsigcpp==2.10.0
pip install --user libsodium==1.0.16
pip install --user libssh2==1.8.0
pip install --user libtiff==4.0.9
pip install --user libtool==2.4.6
pip install --user libuuid==2.32.1
pip install --user libwebp==0.5.2
pip install --user libxcb==1.13
pip install --user libxml2==2.9.8
pip install --user llvmlite==0.26.0
pip install --user locket==0.2.0
pip install --user markdown==2.6.11
pip install --user markupsafe==1.1.0
pip install --user matplotlib
pip install --user metis==5.1.0
pip install --user mistune==0.8.4
pip install --user mkl_fft==1.0.10
pip install --user mkl_random==1.0.2
pip install --user monotonic==1.5
pip install --user mpfr==3.1.5
pip install --user msgpack-python==0.6.0
pip install --user multipledispatch==0.6.0
pip install --user multiprocess==0.70.6.1
pip install --user natsort
pip install --user nbconvert==5.3.1
pip install --user nbformat==4.4.0
pip install --user ncurses==6.1
pip install --user netcdf4
pip install --user nettle==3.3
pip install --user networkx
pip install --user nodejs
pip install --user notebook==5.7.4
pip install --user numba
pip install --user numcodecs==0.6.2
pip install --user numpy
pip install --user olefile==0.46
pip install --user openblas==0.2.20
pip install --user opencv
pip install --user openh264==1.7.0
pip install --user openssl==1.0.2p
pip install --user osqp==0.4.1
pip install --user packaging==18.0
pip install --user pandas
pip install --user pandoc==2.5
pip install --user pandocfilters==1.4.2
pip install --user panel==0.8.0
pip install --user pango==1.40.14
pip install --user papermill
pip install --user param
pip install --user paramnb==2.0.4
pip install --user parso==0.3.1
pip install --user partd==0.3.9
pip install --user patsy==0.5.1
pip install --user pcre==8.41
pip install --user pexpect==4.6.0
pip install --user phantomjs==2.1.1
pip install --user pickleshare==0.7.5
pip install --user pillow==5.2.0
pip install --user pims==0.4.1
pip install --user pip
pip install --user pixman==0.34.0
pip install --user prometheus_client==0.5.0
pip install --user prompt_toolkit==2.0.7
pip install --user psutil==5.4.8
pip install --user pthread-stubs==0.4
pip install --user ptyprocess==0.6.0
pip install --user pycairo==1.13.3
pip install --user pycparser==2.19
pip install --user pyct==0.4.6
pip install --user pyct-core==0.4.6
pip install --user pyfftw
pip install --user pygments==2.3.1
pip install --user pygobject==3.28.2
pip install --user pyopenssl==18.0.0
pip install --user pyparsing==2.3.0
pip install --user pyqt==5.6.0
pip install --user pyrsistent==0.14.8
pip install --user pysocks==1.6.8
pip install --user python-dateutil==2.7.5
pip install --user python-graphviz==0.8.4
pip install --user pytz==2018.7
pip install --user pyviz_comms==0.7.0
pip install --user pywavelets==1.0.1
pip install --user pyyaml==3.13
pip install --user pyzmq==17.1.2
pip install --user qt==5.6.2
pip install --user qtconsole==4.4.3
pip install --user readline==7.0
pip install --user requests==2.21.0
pip install --user s3transfer==0.1.13
pip install --user scikit-image==0.14.1
pip install --user scikit-learn
pip install --user scipy
pip install --user scs
pip install --user seaborn==0.9.0
pip install --user selenium==3.141.0
pip install --user send2trash==1.5.0
pip install --user setuptools==40.6.3
pip install --user sip==4.18.1
pip install --user six==1.12.0
pip install --user slicerator==0.9.8
pip install --user sortedcontainers==2.1.0
pip install --user sparsehash==2.0.3
pip install --user sqlite==3.26.0
pip install --user statsmodels
pip install --user suitesparse==4.5.6
pip install --user tbb==2018_20171205
pip install --user tblib==1.3.2
pip install --user terminado==0.8.1
pip install --user testpath==0.3.1
pip install --user textwrap3==0.9.1
pip install --user tifffile
pip install --user tk==8.6.9
pip install --user toolz==0.9.0
pip install --user tornado==5.1.1
pip install --user tqdm
pip install --user traitlets==4.3.2
pip install --user urllib3==1.24.1
pip install --user wcwidth==0.1.7
pip install --user webencodings==0.5.1
pip install --user wheel==0.32.3
pip install --user widgetsnbextension==3.4.2
pip install --user x264==1!152.20180717
pip install --user xarray
pip install --user xorg-fixesproto==5.0
pip install --user xorg-inputproto==2.3.2
pip install --user xorg-kbproto==1.0.7
pip install --user xorg-libice==1.0.9
pip install --user xorg-libsm==1.2.3
pip install --user xorg-libx11==1.6.6
pip install --user xorg-libxau==1.0.8
pip install --user xorg-libxdmcp==1.1.2
pip install --user xorg-libxext==1.3.3
pip install --user xorg-libxfixes==5.0.3
pip install --user xorg-libxi==1.7.9
pip install --user xorg-libxrender==0.9.10
pip install --user xorg-libxtst==1.2.3
pip install --user xorg-recordproto==1.14.2
pip install --user xorg-renderproto==0.11.1
pip install --user xorg-xextproto==7.3.0
pip install --user xorg-xproto==7.0.31
pip install --user xz==5.2.4
pip install --user yaml==0.1.7
pip install --user zarr
pip install --user zeromq==4.2.5
pip install --user zict==0.1.3
pip install --user zlib==1.2.11
pip install --user cvxcanon==0.1.1
pip install --user intel-openmp==2019.1
pip install --user libboost==1.65.1
pip install --user libgcc-ng==8.2.0
pip install --user libopenblas==0.3.3
pip install --user libopencv==3.4.1
pip install --user libstdcxx-ng==8.2.0
pip install --user mkl==2018.0.3
pip install --user numpy-base==1.15.4
pip install --user py-opencv==3.4.1
pip install --user cudatoolkit==9.0
pip install --user graph-tool==2.26
pip install --user at-spi2-atk==2.26.2
pip install --user at-spi2-core==2.28.0
pip install --user epoxy==1.5.2
pip install --user gtk3==3.22.30
pip install --user pip
pip install --user alabaster==0.7.12
pip install --user babel==2.6.0
pip install --user beautifulsoup4==4.6.3
pip install --user bs4==0.0.1
pip install --user colorlover==0.2.1
pip install --user cufflinks==0.14.6
pip install --user cython==0.29.2
pip install --user faker==1.0.1
pip install --user finance-enums==0.1.0
pip install --user imagesize==1.1.0
pip install --user ipysheet==0.2.0
pip install --user jupyterlab==0.35.4
pip install --user jupyterlab-server==0.2.0
pip install --user lineup-widget==1.0.7
pip install --user medpy
pip install --user mimesis==3.0.0
pip install --user mock==2.0.0
pip install --user msgpack==0.6.0
pip install --user nibabel==2.3.1
pip install --user nose==1.3.7
pip install --user pbr==5.1.1
pip install --user perspective-python==0.1.3
pip install --user plotly==3.4.2
pip install --user pydicom==1.2.1
pip install --user pylantern==0.1.2
pip install --user qgrid==1.1.1
pip install --user retrying==1.3.3
pip install --user sidecar==0.2.0
pip install --user sk-video
pip install --user sklearn==0.0
pip install --user snowballstemmer==1.2.1
pip install --user socketio-client-nexus==0.7.6
pip install --user sphinx==1.8.2
pip install --user sphinxcontrib-websupport==1.1.0
pip install --user text-unidecode==1.2
pip install --user ujson==1.35
pip install --user websocket-client==0.54.0
pip install --user websockets==7.0
pip install --user ffmpeg-python
pip install --user gdown
pip install --user google-api-python-client
pip install --user oauth2client
